version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "PasswordRommanel123"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - rommanel-net

  server:
    image: rommanel-api
    build:
      context: ./server
    ports:
      - "5050:8080"
      - "5051:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=RommanelDb;User=sa;Password=PasswordRommanel123;TrustServerCertificate=True
    depends_on:
      - db
    networks:
      - rommanel-net

  client:
    image: rommanel-web
    build:
      context: ./client
    ports:
      - "4200:4200"
    depends_on:
      - server
    networks:
      - rommanel-net

networks:
  rommanel-net:
    driver: bridge
